"""add notifications_enabled to tenant

Revision ID: e3f9a1b2c4d5
Revises: d2c8g9h3k1j4
Create Date: 2026-03-10 23:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f9a1b2c4d5'
down_revision: Union[str, None] = 'd2c8g9h3k1j4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('notifications_enabled', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'notifications_enabled')
    # ### end Alembic commands ###
